### ISSUE TITLE
Content type Webform defaults not populated on node creation 

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/webform_share#1]
**Steps to reproduce**

1. Create a webform
2. Export the config
3. Paste the config into the content-type "webform default components" text box of a content type enabled for webforms
4. Save the content type
5. Create new content of that type and save
6. Check the Webform tab

**Expected result**
Webform is populated with the config

**Actual result**
Webform is blank with only the site default settings

**Developer Notes**
For anyone looking to fix this, the issue lies in the implementation of `hook_node_insert`.  The config is successfully imported, but when it goes through `backdrop_json_decode` the array comes back as `1`.  This import and decode works fine in the other functions and also in the `devel` modules Execute PHP function.    There are three commented out watchdog statements that you can enable to log the variables (these will be removed once the bug is fixed).

<details>
<summary>Here is a snippet so you can see what functions are being called in `devel`</summary>

```php
$type = 'page'; //change this as needed to match the content type you've enabled webforms on
echo 'JSON FROM CONFIG';
echo PHP_EOL;
$json = config_get('webform_share.settings', 'webform_default_components_' . $type);
echo $json;
echo PHP_EOL;
echo PHP_EOL;
$php = backdrop_json_decode($json);
echo 'DECODED PHP ARRAY (print_r())';
echo PHP_EOL;
print_r($php);
```
</details>

**Comment by indigoxela** [comment]
@yorkshire-pudding I can confirm the problem, but it has absolutely nothing to do with json_decode.

In webform_share_node_insert() you add the webform propery to the node ... but then you don't save it, so data are lost again.

A single `$node->save();` solves the problem for me.

**Comment by indigoxela** [comment]
Looking at Node::save() ... you're probably better off with hook_node_presave...

**Comment by indigoxela** [comment]
> ... probably better off with hook_node_presave...

That does the trick for me, here's a PR: #2

**Comment by yorkshire-pudding** [comment]
Thank you @indigoxela - so  `print_r` doesn't work to output the decoded variable but var_export does.  And thanks for the tip on debug also.
